### API#1 Lowest All-Products Group by category
GET http://localhost:9999/api/product/v1/lowest-products-by-category
###

### API#2 Lowest Price Group by Brand using JPA
GET http://localhost:9999/api/product/v1/lowest-price-by-brand
###

### API#2 Lowest Price Group by Brand using Jdbc Native Query
GET http://localhost:9999/api/product/v2/lowest-price-by-brand
###

### 상품 최저가/최대가 조회 API
GET http://localhost:9999/api/product/v1/min-max-price-by-category?category=상의

### 상품 가격 및 카테고리 수정 후, 결과 확인
GET http://localhost:9999/api/product/v1/min-max-price-by-category?category=바지




